spring:
  profiles:
    active: dev

---

spring:
  profiles:
    group:
      "dev":
        - common
        - dev-db

---

spring:
  config:
    activate:
      on-profile: common

---

server:
  port: 8080

---